export const PACOTE_STATUS = {
    DISPONIVEL: "DISPONIVEL",
    AGUARDANDO_APROVACAO: "AGUARDANDO_APROVACAO",
    AGUARDANDO_COLETA: "AGUARDANDO_COLETA",
    DESTINADO: "DESTINADO",
    A_COLETAR: "A_COLETAR",
    AGUARDANDO_RETIRADA: "AGUARDANDO_RETIRADA",   
    EM_TRANSPORTE: "EM_TRANSPORTE",
    CANCELADO: "CANCELADO"              
};

export const TRANSACAO_TIPO = {
    RESERVA_MATERIAL: "RESERVA_MATERIAL",
    RESERVA_SERVICO: "RESERVA_SERVICO",
    PAGAMENTO_MATERIAL: "PAGAMENTO_MATERIAL",
    PAGAMENTO_SERVICO: "PAGAMENTO_SERVICO",
    ESTORNO_MATERIAL: "ESTORNO_MATERIAL",
    ESTORNO_SERVICO: "ESTORNO_SERVICO",
    COMPRA_MOEDAS: "COMPRA_MOEDAS",
    TRANSFERENCIA: "TRANSFERENCIA",
    COMPRA_ITEM: "COMPRA_ITEM",
    VENDA_ITEM: "VENDA_ITEM",
    BONUS_INICIAL: "BONUS_INICIAL"
};

export const MATERIAL_TIPO = {
    PLASTICO: "PLASTICO",
    PAPEL: "PAPEL",
    VIDRO: "VIDRO",
    METAL: "METAL",
    ELETRONICO: "ELETRONICO"
};